version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:v1.13.4
    container_name: qdrant
    restart: unless-stopped
    volumes:
      - ./docker_data/qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
    environment:
      QDRANT__LOG_LEVEL: "INFO"

  ollama:
    image: ollama/ollama:0.5.12
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      # If you want to set GPU or other config
      # OLLAMA_CUDA: "1"
      OLLAMA_MODEL: "llama2-7b"
      LOG_LEVEL: "INFO"
    volumes:
      - ./docker_data/ollama_models:/root/.ollama

  # Optional: Rust CLI service
  #raggy-notes-cli:
  #  build: .
  #container_name: raggy-notes-cli
  #volumes:
  #  - ./notes:/app/notes # Mount local notes directory
  #depends_on:
  #  - qdrant
  #  - ollama
  #command: ["sleep", "infinity"]
